/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentiment;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStream;
import java.util.HashSet;
import java.util.Iterator;
import java.util.TreeSet;
import javax.swing.JFileChooser;
import opennlp.tools.postag.POSModel;
import opennlp.tools.postag.POSTaggerME;

/**
 *
 * @author User
 */
public class preprocess extends javax.swing.JFrame {

     String filename="";
    /**
     * Creates new form preprocess
     */
    public preprocess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sentiment Analysis");
        setPreferredSize(new java.awt.Dimension(850, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMaximumSize(new java.awt.Dimension(716, 389));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 362));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("CHOOSE THE TWEET FILE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(11, 51, 190, 20);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 120, 120, 50);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("CLEAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 120, 120, 50);

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setText("POS TAG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 120, 120, 50);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 50, 450, 30);

        jLabel8.setBackground(new java.awt.Color(0, 102, 255));
        jLabel8.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jLabel8.setText("   DATA PROCESS");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 20, 240, 27);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\xyz.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(670, 10, 160, 140);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\main_block.jpg")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 180, 630, 180);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
             InputStream modelIn1 = null; 
             
             modelIn1 = new FileInputStream("F:\\BEproject\\en-pos-maxent.bin");
             POSModel model1 = new POSModel(modelIn1);
             POSTaggerME tagger = new POSTaggerME(model1);
             BufferedReader br1=new BufferedReader(new FileReader("F:\\BEproject\\Dictionary\\sentiment\\sentiment\\clean.txt"));
             
             FileWriter fnew1=new FileWriter("pos.txt");
             
             String str1="";
             while((str1=br1.readLine())!=null)
             {
              
                 String[] words=str1.split(" ");
                 
                 for(String eachword: words)
                 {
                     
                      String[]sts={eachword.toString()}; 
                      String tags[] = tagger.tag(sts);
                       
                       for(int j=0;j<tags.length;j++)
                        {
                            fnew1.write(eachword +"  "+tags[j]+"  \r\n");
                        }
                     
                 }
             }
             
             fnew1.close();
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
       
             HashSet stopwords=null;
             
           
        try
        {  
            FileWriter fw=new FileWriter("rem.txt");
           stopwords=new HashSet();
            String dirname1="stops.txt";
            
           FileReader fr = new FileReader(dirname1);
            BufferedReader  br=new BufferedReader(fr);
            String str="";
            String f="";
            while(str!=null)
            {
                str=br.readLine();
                if(str==null)
                    break;
               stopwords.add(str.trim());
            }
       
            fr.close();
            br.close();
            
             TreeSet ts=new TreeSet();
            String s="";
            br=new BufferedReader(new FileReader(filename));

            while(s!=null)
            {               
            
                try
                {
                s=br.readLine();
                
                
                if(s==null)
                    break;
                
                int st=s.lastIndexOf("RT");                
                int nx=0,end=0;
                
                if(st>=0)
                {
                  nx=s.indexOf(":",st+5);
                  st=nx;
                  end=s.indexOf("http",nx+1);
                }
                else
                {
                 st=s.indexOf("2018");
                 end=s.indexOf("https://");
                }
                
                String line="";
                if(end>=0)                    
                {
                    //System.out.println(s);
                    //System.out.println(st+2);
                    //System.out.println(end);
                    line=s.substring(st+2,end);
                    
                    
                }
                else
                {
                    line=s.substring(st+2);
                }
               
                ts.add(line);
                }
            
            catch(Exception e){}  
            }
            
            
                
                
            Iterator it=ts.iterator();
            while(it.hasNext())
            {
                fw.write(it.next().toString());
                fw.write("\r\n");
                fw.flush();
            
            
            
            }
            
            
        fw.close();
        
            
            
            
            
            
             BufferedReader br1=new BufferedReader(new FileReader("rem.txt"));
             
             FileWriter fnew1=new FileWriter("clean.txt");
             
             String str1="";
             while((str1=br1.readLine())!=null)
             {
              
                 String[] words=str1.split(" ");
                 
                 for(String eachword: words)
                 {
                     if(!stopwords.contains(eachword))
                     {
                         fnew1.write(eachword+" ");
                        
                         
                         
                         
                         
                         fnew1.flush();
                     }
                     
                 }
                 
                 fnew1.write("\r\n");
                 fnew1.flush();
                 
             }
             
             fnew1.close();
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            JFileChooser jf=new JFileChooser();
            jf.showOpenDialog(this);
            filename=jf.getSelectedFile().getAbsolutePath();
            jTextField1.setText(filename);
            
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(preprocess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new preprocess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
